version: "3"
services:
  servicea:
    build:
      context: ./ServiceA
      dockerfile: Dockerfile
    # ports:
    #   - "4000:4000"
    network_mode: host
    depends_on:
      - serviceb
  serviceb:
    build:
      context: ./ServiceB
      dockerfile: Dockerfile
    # ports:
    #   - "4000:4000"
    network_mode: host
  serviced:
    build:
      context: ./ServiceD
      dockerfile: Dockerfile
    # ports:
    #   - "50051:50051"
    network_mode: host
  servicec:
    build:
      context: ./ServiceC
      dockerfile: Dockerfile
    # ports:
    #   - "50051:50051"
    network_mode: host  
    depends_on:
      - serviced
  