name: Microservices CI with Podman on UBI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  microservices-ci:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman, Python, and yq
        run: |
          yum install -y podman python3-pip curl git
          pip3 install yq podman-compose

      - name: Build all service images
        run: |
          # Example: build ServiceA and ServiceD
          podman build -t servicea ./ServiceA
          podman build -t serviced ./ServiceD

      - name: Update podman-composed.yaml to use local images
        run: |
          yq -i '.services.servicea.image = "servicea"' podman-composed.yaml
          yq -i '.services.serviced.image = "serviced"' podman-composed.yaml

      - name: Start services with podman-compose
        run: |
          export PATH=$PATH:$HOME/.local/bin
          podman-compose -f podman-composed.yaml up -d

      - name: Wait for services to start
        run: sleep 15

      - name: Run integration / health checks
        run: |
          # Example: check gRPC port (replace with your actual health check)
          curl -f http://localhost:50051 || echo "gRPC service may not have HTTP endpoint"

      - name: Tear down
        if: always()
        run: |
          export PATH=$PATH:$HOME/.local/bin
          podman-compose -f podman-composed.yaml down
