name: Microservices CI with Podman

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  microservices-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Install Podman, Python 3, and podman-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y podman python3-pip git
          pip3 install --user podman-compose
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Start services with podman-compose
        run: |
          podman-compose -f podman-composed.yaml up --build

      - name: Wait for services to start
        run: sleep 15

      - name: Run integration / health checks
        run: |
          curl -f http://localhost:50051 || echo "gRPC service may not have HTTP endpoint"

      - name: Tear down
        if: always()
        run: |
          podman-compose -f podman-composed.yaml down
