
name: Microservices CI with Podman

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  microservices-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Install Podman, Python 3, and podman-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y podman python3-pip git
          pip3 install --user podman-compose
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build services with podman-compose
        run: |
          podman-compose -f podman-composed.yaml build 
      - name: Start services with podman-compose
        run: |
          podman kill --all
          podman-compose -f podman-composed.yaml up -d 
      - name: Wait for services to start
        run: sleep 15

      - name: Run integration / health checks
        id: grpc-test
        run: |
          set -o pipefail
          podman-compose -f podman-composed.yaml run --rm servicec 2>&1 | tee micro_servicec.log

      - name: Check Service C result and report error
        if: failure()  # Only runs if the previous step failed
        run: |
            echo "::error ::Service C failed! Output below:"
            cat micro_servicec.log
            exit 1
      - name: Tear down
        if: always()
        run: |
          podman-compose -f podman-composed.yaml down
